name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint backend
        run: cd backend && flake8 .

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Lint frontend
        run: cd frontend && npx eslint src --ext .js,.jsx

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies for testing
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run backend tests
        run: cd backend && pytest

  docker:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker image tag
        run: echo "SHA_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/infilect-backend:${{ env.SHA_TAG }} ./backend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/infilect-backend:${{ env.SHA_TAG }}

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/infilect-frontend:${{ env.SHA_TAG }} ./frontend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/infilect-frontend:${{ env.SHA_TAG }}
