apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: metrics-app
spec:
  selector:
    app: metrics-app
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
