apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: metrics-app
spec:
  selector:
    app: metrics-app
    component: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
